# Site settings
title: "Peter Viechnicki"
description: "Research Homepage"
email: pviechnicki2@gmail.com
github: pviechnicki.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Personal information
author:
  name: "Peter Viechnicki"
  bio: "Dr. Viechnicki is a Research Scientist who recently completed his five-year term as
  Academic Center Director at the Johns Hopkins Whiting School of Engineering with a passion
  for enabling teams of smart people to deliver key research outcomes. Over the course of his
  twenty-year career he has led progressively larger teams of research scientists, engineers,
  linguists, and data scientists at a Tier-1 research university, in the consulting industry,
  and in government.
  As a phonetician and computational linguist Dr. Viechnicki pursues fundamental empirical
  research on how humans use language, with an emphasis on speech production. He has a
  particular interest in developing new empirical techniques to investigate questions of
  long-standing interest to the disciplines of linguistics and cognitive science, such as
  cognitive representations of speech production targets and global assessments of rates
  of linguistic change."
  location: "Washington, DC"
  github: "pviechnicki.github.io"
  linkedin: https://www.linkedin.com/in/peter-viechnicki-63226435/
  
